"""empty message

Revision ID: 1fe59e753d79
Revises: 573c5f281d4e
Create Date: 2021-04-12 15:49:09.493886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe59e753d79'
down_revision = '573c5f281d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('components', sa.String(length=10000), nullable=True))
    op.add_column('robot', sa.Column('components_status', sa.String(length=10000), nullable=True))
    op.drop_column('robot', 'lbr')
    op.drop_column('robot', 'kmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('kmp', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('lbr', sa.BOOLEAN(), nullable=True))
    op.drop_column('robot', 'components_status')
    op.drop_column('robot', 'components')
    # ### end Alembic commands ###
