"""commands and robots table

Revision ID: 573c5f281d4e
Revises: 
Create Date: 2021-03-23 15:53:42.049252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573c5f281d4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('command', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('command')
    )
    op.create_table('robot',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lbr', sa.Boolean(), nullable=True),
    sa.Column('kmp', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot')
    op.drop_table('command')
    # ### end Alembic commands ###
