"""empty message

Revision ID: d85878e4bff4
Revises: adf1a3728df5
Create Date: 2021-04-30 14:41:25.334972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85878e4bff4'
down_revision = 'adf1a3728df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('operator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'operator')
    # ### end Alembic commands ###
