# Generated by Django 3.1.3 on 2021-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.IntegerField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('lbr', models.CharField(max_length=30)),
                ('kmp', models.CharField(max_length=30)),
            ],
        ),
    ]
