# Generated by Django 3.1.3 on 2021-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas_api', '0002_robot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='robot_id',
        ),
        migrations.AlterField(
            model_name='robot',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
