# Generated by Django 3.1.3 on 2021-02-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas_api', '0003_auto_20210202_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='kmp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='lbr',
            field=models.BooleanField(default=False),
        ),
    ]
