# Generated by Django 3.1.3 on 2020-11-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_commands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commands',
            new_name='Command',
        ),
    ]
