"""update robot table

Revision ID: 11be67be902f
Revises: 2a569386cc0e
Create Date: 2021-04-12 15:59:12.246790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11be67be902f'
down_revision = '2a569386cc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'components_status')
    op.drop_column('robot', 'lbr')
    op.drop_column('robot', 'kmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('kmp', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('lbr', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('components_status', sa.VARCHAR(length=10000), nullable=True))
    # ### end Alembic commands ###
