"""update robot table

Revision ID: 2a569386cc0e
Revises: 1fe59e753d79
Create Date: 2021-04-12 15:54:42.343671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a569386cc0e'
down_revision = '1fe59e753d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('status', sa.String(length=10000), nullable=True))
    op.drop_column('robot', 'kmp')
    op.drop_column('robot', 'components_status')
    op.drop_column('robot', 'lbr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('lbr', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('components_status', sa.VARCHAR(length=10000), nullable=True))
    op.add_column('robot', sa.Column('kmp', sa.BOOLEAN(), nullable=True))
    op.drop_column('robot', 'status')
    # ### end Alembic commands ###
