"""empty message

Revision ID: 3697fb79114d
Revises: a789f120e30a
Create Date: 2021-04-20 10:53:43.158049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3697fb79114d'
down_revision = 'a789f120e30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('stream_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'stream_port')
    # ### end Alembic commands ###
