"""empty message

Revision ID: 3db19bd1c5d7
Revises: 745e349e7017
Create Date: 2021-04-13 11:13:23.053098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db19bd1c5d7'
down_revision = '745e349e7017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'kmp')
    op.drop_column('robot', 'lbr')
    op.drop_column('robot', 'components_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('components_status', sa.VARCHAR(length=10000), nullable=True))
    op.add_column('robot', sa.Column('lbr', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('kmp', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
