"""update robot table

Revision ID: 745e349e7017
Revises: 11be67be902f
Create Date: 2021-04-12 16:03:58.228612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745e349e7017'
down_revision = '11be67be902f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'components_status')
    op.drop_column('robot', 'lbr')
    op.drop_column('robot', 'kmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('kmp', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('lbr', sa.BOOLEAN(), nullable=True))
    op.add_column('robot', sa.Column('components_status', sa.VARCHAR(length=10000), nullable=True))
    # ### end Alembic commands ###
